# Generated by Django 5.1.4 on 2026-10-09 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='titulo del puesto')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='ciudad')),
                ('openings', models.PositiveSmallIntegerField(default=1, verbose_name='vacantes disponibles')),
                ('modality', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('HIBRIDA', 'Híbrida'), ('REMOTA', 'Remota')], default='PRESENCIAL', max_length=20, verbose_name='modalidad')),
                ('stage', models.CharField(choices=[('LECTIVA', 'Lectiva'), ('PRODUCTIVA', 'Productiva')], default='PRODUCTIVA', max_length=20, verbose_name='etapa')),
                ('duration_months', models.PositiveSmallIntegerField(default=6, verbose_name='duracion (meses)')),
                ('stipend', models.CharField(blank=True, max_length=120, verbose_name='apoyo de sostenimiento')),
                ('description', models.TextField(blank=True, max_length=4000, verbose_name='descripcion')),
                ('requirements', models.JSONField(blank=True, default=list, verbose_name='requisitos')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='habilidades')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Activa'), ('RECHAZADA', 'Rechazada'), ('PAUSADA', 'En pausa')], default='BORRADOR', max_length=20, verbose_name='estado')),
                ('rejection_reason', models.CharField(blank=True, max_length=500, verbose_name='motivo del rechazo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisada el')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada a revision el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='companies.companyprofile', verbose_name='empresa')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
            ],
            options={
                'verbose_name': 'vacante',
                'verbose_name_plural': 'vacantes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'modality', 'stage'], name='jobs_vacanc_status_6f2c0c_idx')],
            },
        ),
    ]
