# Generated by Django 5.1.4 on 2026-10-09 23:08

import apps.companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='razon social')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='ciudad')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='sitio web')),
                ('about', models.TextField(blank=True, max_length=2000, verbose_name='sobre la empresa')),
                ('sectors', models.JSONField(blank=True, default=list, verbose_name='sectores')),
                ('logo', models.ImageField(blank=True, upload_to=apps.companies.models.ruta_logo, verbose_name='logo')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('rejection_reason', models.CharField(blank=True, max_length=500, verbose_name='motivo del rechazo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisada el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['-created_at'],
            },
        ),
    ]
