# Generated by Django 5.1.4 on 2026-10-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APLICADO', 'Aplicado'), ('EN_REVISION', 'En revisión'), ('ENTREVISTA', 'Entrevista'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='APLICADO', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de postulacion')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='ultimo cambio de estado')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile', verbose_name='estudiante')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.vacancy', verbose_name='vacante')),
            ],
            options={
                'verbose_name': 'postulación',
                'verbose_name_plural': 'postulaciones',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'vacancy'), name='postulacion_unica')],
            },
        ),
    ]
