# Generated by Django 5.1.4 on 2026-10-09 23:08

import apps.students.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=150, verbose_name='institucion')),
                ('program', models.CharField(blank=True, max_length=150, verbose_name='carrera o programa')),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='semestre')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='ciudad')),
                ('about', models.TextField(blank=True, max_length=1500, verbose_name='sobre mi')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='habilidades')),
                ('cv', models.FileField(blank=True, upload_to=apps.students.models.ruta_hoja_de_vida, verbose_name='hoja de vida (PDF)')),
                ('cv_filename', models.CharField(blank=True, max_length=255, verbose_name='nombre original del PDF')),
                ('cv_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='tamano del PDF (bytes)')),
                ('cv_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de estudiante',
                'verbose_name_plural': 'perfiles de estudiante',
            },
        ),
    ]
